import type { User, Job, Bid, Invoice, Territory, BidTemplate } from './types'
import { calculateJobSize } from './types'

let demoDataInitialized = false

export const DEMO_USERS: Record<'homeowner' | 'contractor' | 'operator', User> = {
  homeowner: {
    id: 'demo-homeowner-001',
    email: 'demo.homeowner@fairtradeworker.com',
    fullName: 'Sarah Johnson',
    role: 'homeowner',
    isPro: false,
    performanceScore: 0,
    bidAccuracy: 0,
    isOperator: false,
    referralEarnings: 0,
    contractorInviteCount: 0,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  contractor: {
    id: 'demo-contractor-001',
    email: 'demo.contractor@fairtradeworker.com',
    fullName: 'Mike Rodriguez',
    role: 'contractor',
    territoryId: 1,
    isPro: false,
    performanceScore: 0.85,
    bidAccuracy: 0.92,
    isOperator: false,
    referralEarnings: 50,
    contractorInviteCount: 3,
    companyName: 'Rodriguez Home Services',
    companyAddress: '456 Commerce St\nDowntown, 78701',
    companyPhone: '(512) 555-0142',
    companyEmail: 'contact@rodriguezhome.com',
    taxId: '74-1234567',
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  operator: {
    id: 'demo-operator-001',
    email: 'demo.operator@fairtradeworker.com',
    fullName: 'James Chen',
    role: 'operator',
    territoryId: 1,
    isPro: true,
    proSince: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    performanceScore: 0.95,
    bidAccuracy: 0.88,
    isOperator: true,
    referralEarnings: 0,
    contractorInviteCount: 0,
    createdAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
  },
}

export const DEMO_JOBS: Job[] = [
  {
    id: 'demo-job-001',
    homeownerId: 'demo-homeowner-001',
    title: 'Kitchen Faucet Replacement',
    description: 'My kitchen faucet is leaking from the base and needs to be replaced. It\'s a standard single-handle faucet.',
    mediaType: 'photo',
    photos: [
      'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800&q=80',
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80',
    ],
    aiScope: {
      scope: 'Replace leaking kitchen faucet cartridge and install new single-handle faucet. Includes shutoff valve inspection and water line check.',
      priceLow: 120,
      priceHigh: 180,
      materials: ['Moen cartridge', 'Basin wrench', 'Plumber\'s grease', 'Teflon tape'],
    },
    size: calculateJobSize(180),
    status: 'open',
    territoryId: 1,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    bids: [
      {
        id: 'demo-bid-001',
        jobId: 'demo-job-001',
        contractorId: 'demo-contractor-002',
        contractorName: 'Tom\'s Plumbing',
        amount: 150,
        message: 'I can get this done same-day with a 1-year warranty on parts and labor.',
        status: 'pending',
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    id: 'demo-job-002',
    homeownerId: 'demo-homeowner-002',
    title: 'Drywall Repair in Living Room',
    description: 'Hole in drywall from moving furniture. About 4 inches diameter.',
    mediaType: 'photo',
    photos: [
      'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=800&q=80',
    ],
    aiScope: {
      scope: 'Patch 4-inch drywall hole with mesh tape, joint compound, sand smooth, prime and paint to match existing wall.',
      priceLow: 80,
      priceHigh: 130,
      materials: ['Drywall patch kit', 'Joint compound', 'Mesh tape', 'Sandpaper', 'Paint primer', 'Wall paint'],
    },
    size: calculateJobSize(130),
    status: 'open',
    territoryId: 1,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    bids: [],
  },
  {
    id: 'demo-job-003',
    homeownerId: 'demo-homeowner-001',
    title: 'Ceiling Fan Installation',
    description: 'Need to install a new ceiling fan in master bedroom. Existing light fixture to be removed.',
    mediaType: 'photo',
    photos: [
      'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=800&q=80',
      'https://images.unsplash.com/photo-1505691723518-36a5ac3be353?w=800&q=80',
    ],
    aiScope: {
      scope: 'Remove existing light fixture, install ceiling fan support bracket, wire and mount 52-inch ceiling fan with light kit, test all functions.',
      priceLow: 150,
      priceHigh: 220,
      materials: ['Ceiling fan support brace', 'Wire nuts', 'Mounting hardware', 'Electrical tape'],
    },
    size: calculateJobSize(220),
    status: 'open',
    territoryId: 1,
    createdAt: new Date().toISOString(),
    bids: [],
  },
  {
    id: 'demo-job-004',
    homeownerId: 'demo-homeowner-003',
    title: 'Outdoor Deck Staining',
    description: 'Need my 12x16 deck cleaned, sanded, and re-stained. Wood is weathered but structurally sound.',
    mediaType: 'photo',
    photos: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80',
    ],
    aiScope: {
      scope: 'Power wash 192 sq ft deck, sand surface, apply wood conditioner, and two coats of semi-transparent deck stain.',
      priceLow: 450,
      priceHigh: 650,
      materials: ['Deck cleaner', 'Wood conditioner', 'Deck stain (2 gallons)', 'Sandpaper/pads', 'Brushes and rollers'],
    },
    size: calculateJobSize(650),
    status: 'in-progress',
    territoryId: 2,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    bids: [
      {
        id: 'demo-bid-004',
        jobId: 'demo-job-004',
        contractorId: 'demo-contractor-001',
        contractorName: 'Mike Rodriguez',
        amount: 525,
        message: 'I have 15 years of deck refinishing experience. Can start next week and complete in 2 days weather permitting.',
        status: 'accepted',
        createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    id: 'demo-job-005',
    homeownerId: 'demo-homeowner-002',
    title: 'Leaky Toilet Fix',
    description: 'Toilet running constantly. Need quick repair.',
    mediaType: 'photo',
    photos: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80',
    ],
    aiScope: {
      scope: 'Replace faulty flapper valve and adjust fill valve. Test for proper shutoff.',
      priceLow: 75,
      priceHigh: 120,
      materials: ['Flapper valve', 'Fill valve kit', 'Wax ring (if needed)'],
    },
    size: calculateJobSize(120),
    status: 'open',
    territoryId: 1,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    bids: [],
  },
  {
    id: 'demo-job-006',
    homeownerId: 'demo-homeowner-001',
    title: 'Garage Door Spring Replacement',
    description: 'Garage door won\'t open. Cable looks broken.',
    mediaType: 'photo',
    photos: [
      'https://images.unsplash.com/photo-1617083278530-6a524d3c90e5?w=800&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    ],
    aiScope: {
      scope: 'Replace broken torsion spring, inspect and adjust cables, lubricate all moving parts, test safety features.',
      priceLow: 250,
      priceHigh: 380,
      materials: ['Torsion spring set', 'Cable kit', 'Lubricant', 'Safety tools'],
    },
    size: calculateJobSize(380),
    status: 'open',
    territoryId: 1,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    bids: [
      {
        id: 'demo-bid-006',
        jobId: 'demo-job-006',
        contractorId: 'demo-contractor-003',
        contractorName: 'Garage Door Pros',
        amount: 325,
        message: 'We specialize in garage door repairs. Can come today with all parts in our truck.',
        status: 'pending',
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    id: 'demo-job-007',
    homeownerId: 'demo-homeowner-003',
    title: 'Full Kitchen Remodel',
    description: 'Complete kitchen renovation - new cabinets, countertops, appliances, flooring, and lighting.',
    mediaType: 'photo',
    photos: [
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
      'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=800&q=80',
      'https://images.unsplash.com/photo-1556911261-6bd341186b2f?w=800&q=80',
      'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=800&q=80',
    ],
    aiScope: {
      scope: 'Full kitchen remodel including cabinet removal and installation, granite countertops, tile backsplash, new appliances, hardwood flooring, recessed lighting, and painting.',
      priceLow: 18000,
      priceHigh: 28000,
      materials: ['Custom cabinets', 'Granite countertops', 'Tile', 'Hardwood flooring', 'Appliances', 'LED recessed lights', 'Plumbing fixtures', 'Paint'],
    },
    size: calculateJobSize(28000),
    status: 'open',
    territoryId: 2,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    bids: [],
  },
  {
    id: 'demo-job-008',
    homeownerId: 'demo-homeowner-001',
    title: 'Gutter Cleaning',
    description: 'Gutters overflowing. Need cleaned and checked for damage.',
    mediaType: 'photo',
    photos: [
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&q=80',
    ],
    aiScope: {
      scope: 'Clean all gutters and downspouts, inspect for damage, flush drainage, minor repairs as needed.',
      priceLow: 150,
      priceHigh: 225,
      materials: ['Gutter sealant', 'Downspout straps', 'Gutter guards (optional)'],
    },
    size: calculateJobSize(225),
    status: 'open',
    territoryId: 1,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    bids: [
      {
        id: 'demo-bid-008',
        jobId: 'demo-job-008',
        contractorId: 'demo-contractor-001',
        contractorName: 'Mike Rodriguez',
        amount: 180,
        message: 'I can do this tomorrow morning. Includes full inspection and photos of any issues found.',
        status: 'pending',
        createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    id: 'demo-job-009',
    homeownerId: 'demo-homeowner-002',
    title: 'Replace Light Switch',
    description: 'Living room light switch is loose and sparking. Need immediate replacement.',
    mediaType: 'photo',
    photos: [
      'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80',
    ],
    aiScope: {
      scope: 'Replace faulty light switch with new Decora-style switch, check wiring, test functionality.',
      priceLow: 60,
      priceHigh: 95,
      materials: ['Decora switch', 'Wire nuts', 'Electrical tape'],
    },
    size: calculateJobSize(95),
    status: 'open',
    territoryId: 1,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    bids: [],
  },
  {
    id: 'demo-job-010',
    homeownerId: 'demo-homeowner-003',
    title: 'Bathroom Sink Clog',
    description: 'Bathroom sink draining very slowly. Likely hair clog.',
    mediaType: 'photo',
    photos: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80',
    ],
    aiScope: {
      scope: 'Snake bathroom drain, remove P-trap to clear clog, clean drain assembly, test flow.',
      priceLow: 85,
      priceHigh: 140,
      materials: ['Drain snake', 'P-trap gaskets', 'Drain cleaner'],
    },
    size: calculateJobSize(140),
    status: 'open',
    territoryId: 1,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    bids: [],
  },
  {
    id: 'demo-job-011',
    homeownerId: 'demo-homeowner-001',
    title: 'Weather Stripping Replacement',
    description: 'Front door has drafts. Need weather stripping replaced.',
    mediaType: 'photo',
    photos: [
      'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&q=80',
    ],
    aiScope: {
      scope: 'Remove old weather stripping, clean door frame, install new adhesive weather stripping, adjust door sweep.',
      priceLow: 75,
      priceHigh: 120,
      materials: ['Weather stripping', 'Door sweep', 'Adhesive'],
    },
    size: calculateJobSize(120),
    status: 'open',
    territoryId: 1,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    bids: [],
  },
  {
    id: 'demo-job-012',
    homeownerId: 'demo-homeowner-002',
    title: 'Outlet Not Working',
    description: 'Kitchen outlet stopped working. Tried reset button, no luck.',
    mediaType: 'photo',
    photos: [
      'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80',
    ],
    aiScope: {
      scope: 'Diagnose electrical issue, replace faulty GFCI outlet, test circuit, verify code compliance.',
      priceLow: 90,
      priceHigh: 150,
      materials: ['GFCI outlet', 'Wire connectors', 'Faceplate'],
    },
    size: calculateJobSize(150),
    status: 'open',
    territoryId: 1,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    bids: [],
  },
  {
    id: 'demo-job-013',
    homeownerId: 'demo-homeowner-003',
    title: 'Doorbell Installation',
    description: 'Want to install a Ring doorbell. Need wiring checked.',
    mediaType: 'photo',
    photos: [
      'https://images.unsplash.com/photo-1558002038-1055907df827?w=800&q=80',
    ],
    aiScope: {
      scope: 'Check existing doorbell wiring voltage, install Ring doorbell, configure WiFi, test functionality.',
      priceLow: 100,
      priceHigh: 160,
      materials: ['Doorbell transformer (if needed)', 'Wire', 'Mounting hardware'],
    },
    size: calculateJobSize(160),
    status: 'open',
    territoryId: 1,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    bids: [],
  },
  {
    id: 'demo-job-014',
    homeownerId: 'demo-homeowner-001',
    title: 'Leaking Shower Head',
    description: 'Shower head drips constantly even when turned off.',
    mediaType: 'photo',
    photos: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80',
    ],
    aiScope: {
      scope: 'Replace shower head washer or cartridge, check for pipe corrosion, install new shower head if needed.',
      priceLow: 70,
      priceHigh: 130,
      materials: ['Shower head', 'Washers', 'Teflon tape', 'Pipe wrench'],
    },
    size: calculateJobSize(130),
    status: 'open',
    territoryId: 1,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    bids: [],
  },
  {
    id: 'demo-job-015',
    homeownerId: 'demo-homeowner-002',
    title: 'Replace Cabinet Hinges',
    description: 'Several kitchen cabinet hinges are loose or broken.',
    mediaType: 'photo',
    photos: [
      'https://images.unsplash.com/photo-1556912167-f556f1f39faa?w=800&q=80',
    ],
    aiScope: {
      scope: 'Replace 8 cabinet hinges, adjust cabinet doors for proper alignment, tighten all hardware.',
      priceLow: 120,
      priceHigh: 180,
      materials: ['Cabinet hinges (8)', 'Wood screws', 'Wood filler'],
    },
    size: calculateJobSize(180),
    status: 'open',
    territoryId: 1,
    createdAt: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    bids: [],
  },
  // MEDIUM JOBS ($300-$1500)
  {
    id: 'demo-job-016',
    homeownerId: 'demo-homeowner-001',
    title: 'Bathroom Vanity Installation',
    description: 'Need to replace old bathroom vanity with new 48-inch double sink vanity. Includes plumbing hookup.',
    mediaType: 'photo',
    photos: [
      'https://images.unsplash.com/photo-1620626011761-996317b8d101?w=800&q=80',
      'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&q=80',
    ],
    aiScope: {
      scope: 'Remove existing vanity, install new 48-inch double sink vanity with faucets, connect plumbing, caulk and seal. Includes disposal of old vanity.',
      priceLow: 450,
      priceHigh: 750,
      materials: ['48" vanity', 'Double sink faucets', 'P-trap kit', 'Supply lines', 'Caulk', 'Plumber\'s putty'],
    },
    size: calculateJobSize(750),
    status: 'open',
    territoryId: 1,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
    bids: [],
  },
  {
    id: 'demo-job-017',
    homeownerId: 'demo-homeowner-002',
    title: 'Interior Paint - Living Room & Kitchen',
    description: 'Paint living room and kitchen. Walls, trim, and ceiling. Two colors for walls, white for trim.',
    mediaType: 'photo',
    photos: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
      'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800&q=80',
    ],
    aiScope: {
      scope: 'Paint living room (400 sq ft) and kitchen (200 sq ft). Includes walls, trim, and ceiling. Two coats on walls, one on trim. Includes prep work, taping, and cleanup.',
      priceLow: 600,
      priceHigh: 950,
      materials: ['Paint (walls)', 'Paint (trim)', 'Primer', 'Paint brushes and rollers', 'Drop cloths', 'Painter\'s tape'],
    },
    size: calculateJobSize(950),
    status: 'open',
    territoryId: 1,
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(), // 30 minutes ago
    bids: [],
  },
  {
    id: 'demo-job-018',
    homeownerId: 'demo-homeowner-003',
    title: 'Tile Backsplash Installation',
    description: 'Install subway tile backsplash in kitchen. About 30 square feet behind stove and sink area.',
    mediaType: 'photo',
    photos: [
      'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800&q=80',
      'https://images.unsplash.com/photo-1556911261-6bd341186b2f?w=800&q=80',
    ],
    aiScope: {
      scope: 'Install 30 sq ft subway tile backsplash. Includes removal of old backsplash, surface prep, tile installation, grouting, and sealing.',
      priceLow: 550,
      priceHigh: 850,
      materials: ['Subway tiles (30 sq ft)', 'Tile adhesive', 'Grout', 'Tile sealer', 'Spacers', 'Trowel'],
    },
    size: calculateJobSize(850),
    status: 'open',
    territoryId: 2,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    bids: [],
  },
  {
    id: 'demo-job-019',
    homeownerId: 'demo-homeowner-001',
    title: 'Hardwood Floor Refinishing',
    description: 'Refinish hardwood floors in 3 bedrooms. Total about 600 square feet. Sand, stain, and polyurethane.',
    mediaType: 'photo',
    photos: [
      'https://images.unsplash.com/photo-1581539250439-c96689b516dd?w=800&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
    ],
    aiScope: {
      scope: 'Refinish 600 sq ft of hardwood floors in 3 bedrooms. Includes sanding, staining, and 3 coats of polyurethane. Furniture moving and replacement included.',
      priceLow: 1200,
      priceHigh: 1800,
      materials: ['Floor stain', 'Polyurethane (3 coats)', 'Sandpaper', 'Tack cloths', 'Applicators'],
    },
    size: calculateJobSize(1800),
    status: 'open',
    territoryId: 1,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(), // 1 hour ago
    bids: [],
  },
  {
    id: 'demo-job-020',
    homeownerId: 'demo-homeowner-002',
    title: 'Window Replacement - 5 Windows',
    description: 'Replace 5 old single-pane windows with energy-efficient double-pane windows. Standard sizes.',
    mediaType: 'photo',
    photos: [
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&q=80',
      'https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&q=80',
    ],
    aiScope: {
      scope: 'Replace 5 single-pane windows with energy-efficient double-pane windows. Includes removal, installation, caulking, and trim work.',
      priceLow: 800,
      priceHigh: 1200,
      materials: ['5 double-pane windows', 'Window flashing', 'Caulk', 'Trim boards', 'Insulation'],
    },
    size: calculateJobSize(1200),
    status: 'open',
    territoryId: 1,
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(), // 45 minutes ago
    bids: [],
  },
  {
    id: 'demo-job-021',
    homeownerId: 'demo-homeowner-003',
    title: 'Deck Repair & Staining',
    description: 'Repair loose boards and railings on 16x20 deck, then power wash and stain entire deck.',
    mediaType: 'photo',
    photos: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
    ],
    aiScope: {
      scope: 'Repair 5 loose deck boards and 2 railings, power wash 320 sq ft deck, sand rough areas, apply wood conditioner, and 2 coats of deck stain.',
      priceLow: 900,
      priceHigh: 1400,
      materials: ['Deck boards (5)', 'Railing hardware', 'Deck cleaner', 'Wood conditioner', 'Deck stain (3 gallons)', 'Sandpaper'],
    },
    size: calculateJobSize(1400),
    status: 'open',
    territoryId: 2,
    createdAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(), // 20 minutes ago
    bids: [],
  },
  {
    id: 'demo-job-022',
    homeownerId: 'demo-homeowner-001',
    title: 'Electrical Panel Upgrade',
    description: 'Upgrade 100-amp electrical panel to 200-amp. Includes new panel, breakers, and inspection.',
    mediaType: 'photo',
    photos: [
      'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80',
    ],
    aiScope: {
      scope: 'Upgrade electrical service from 100-amp to 200-amp. Includes new panel, breakers, main disconnect, grounding, and electrical inspection.',
      priceLow: 1100,
      priceHigh: 1600,
      materials: ['200-amp panel', 'Circuit breakers', 'Main disconnect', 'Grounding equipment', 'Wire', 'Conduit'],
    },
    size: calculateJobSize(1600),
    status: 'open',
    territoryId: 1,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    bids: [],
  },
  // LARGE JOBS ($1500+)
  {
    id: 'demo-job-023',
    homeownerId: 'demo-homeowner-003',
    title: 'Master Bathroom Remodel',
    description: 'Complete master bathroom renovation. New vanity, toilet, tub/shower, tile, lighting, and fixtures.',
    mediaType: 'photo',
    photos: [
      'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&q=80',
      'https://images.unsplash.com/photo-1620626011761-996317b8d101?w=800&q=80',
      'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800&q=80',
    ],
    aiScope: {
      scope: 'Complete master bathroom renovation including removal of old fixtures, new vanity with double sinks, new toilet, tub/shower combo with tile surround, new flooring, lighting, mirrors, and all plumbing/electrical work.',
      priceLow: 8500,
      priceHigh: 12500,
      materials: ['Vanity', 'Toilet', 'Tub/shower', 'Tile (floor and walls)', 'Lighting fixtures', 'Plumbing fixtures', 'Paint', 'Mirrors'],
    },
    size: calculateJobSize(12500),
    status: 'open',
    territoryId: 2,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(), // 3 hours ago
    bids: [],
  },
  {
    id: 'demo-job-024',
    homeownerId: 'demo-homeowner-001',
    title: 'Roof Replacement - 2000 sq ft',
    description: 'Replace entire roof. Remove old shingles, repair decking as needed, install new shingles and gutters.',
    mediaType: 'photo',
    photos: [
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&q=80',
      'https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&q=80',
    ],
    aiScope: {
      scope: 'Complete roof replacement on 2000 sq ft home. Remove old shingles, inspect and repair decking, install new architectural shingles, replace gutters and downspouts, install new flashing.',
      priceLow: 12000,
      priceHigh: 18000,
      materials: ['Architectural shingles (2000 sq ft)', 'Underlayment', 'Gutters and downspouts', 'Flashing', 'Nails', 'Vent boots'],
    },
    size: calculateJobSize(18000),
    status: 'open',
    territoryId: 1,
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(), // 15 minutes ago
    bids: [],
  },
  {
    id: 'demo-job-025',
    homeownerId: 'demo-homeowner-002',
    title: 'HVAC System Replacement',
    description: 'Replace old HVAC system with new high-efficiency unit. Includes furnace, AC, and ductwork updates.',
    mediaType: 'photo',
    photos: [
      'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80',
    ],
    aiScope: {
      scope: 'Replace entire HVAC system with new high-efficiency furnace and AC unit. Includes removal of old system, installation of new units, ductwork modifications, electrical connections, and system testing.',
      priceLow: 6500,
      priceHigh: 9500,
      materials: ['High-efficiency furnace', 'AC condenser unit', 'Ductwork materials', 'Thermostat', 'Refrigerant', 'Electrical components'],
    },
    size: calculateJobSize(9500),
    status: 'open',
    territoryId: 1,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    bids: [],
  },
  {
    id: 'demo-job-026',
    homeownerId: 'demo-homeowner-003',
    title: 'Basement Finishing - 800 sq ft',
    description: 'Finish basement into family room. Includes framing, drywall, electrical, flooring, and paint.',
    mediaType: 'photo',
    photos: [
      'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=800&q=80',
      'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800&q=80',
    ],
    aiScope: {
      scope: 'Finish 800 sq ft basement into family room. Includes framing, insulation, drywall installation and finishing, electrical work (outlets and lighting), flooring installation, and painting.',
      priceLow: 7500,
      priceHigh: 11000,
      materials: ['Lumber for framing', 'Insulation', 'Drywall', 'Electrical supplies', 'Flooring', 'Paint', 'Trim'],
    },
    size: calculateJobSize(11000),
    status: 'open',
    territoryId: 2,
    createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    bids: [],
  },
  {
    id: 'demo-job-027',
    homeownerId: 'demo-homeowner-001',
    title: 'Siding Replacement - Front & Back',
    description: 'Replace siding on front and back of house. About 1200 square feet. Vinyl siding.',
    mediaType: 'photo',
    photos: [
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&q=80',
    ],
    aiScope: {
      scope: 'Replace siding on front and back of house (1200 sq ft). Remove old siding, install new vinyl siding, replace trim, install new soffits and fascia.',
      priceLow: 4500,
      priceHigh: 6800,
      materials: ['Vinyl siding (1200 sq ft)', 'Trim boards', 'Soffits and fascia', 'House wrap', 'Nails and fasteners'],
    },
    size: calculateJobSize(6800),
    status: 'open',
    territoryId: 1,
    createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(), // 5 minutes ago
    bids: [],
  },
]

export const DEMO_INVOICES: Invoice[] = [
  {
    id: 'demo-invoice-001',
    contractorId: 'demo-contractor-001',
    jobId: 'demo-job-004',
    jobTitle: 'Outdoor Deck Staining',
    lineItems: [
      { description: 'Labor (8 hours)', quantity: 8, rate: 50, total: 400 },
      { description: 'Deck stain materials', quantity: 1, rate: 125, total: 125 },
    ],
    subtotal: 525,
    taxRate: 0,
    taxAmount: 0,
    total: 525,
    status: 'sent',
    dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    sentDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    isProForma: false,
    lateFeeApplied: false,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-invoice-002',
    contractorId: 'demo-contractor-001',
    jobId: 'demo-job-005',
    jobTitle: 'Bathroom Tile Repair',
    lineItems: [
      { description: 'Tile replacement labor', quantity: 4, rate: 50, total: 200 },
      { description: 'Ceramic tiles', quantity: 1, rate: 75, total: 75 },
    ],
    subtotal: 275,
    taxRate: 0,
    taxAmount: 0,
    total: 275,
    status: 'paid',
    dueDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    sentDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    paidDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    isProForma: false,
    lateFeeApplied: false,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const DEMO_TERRITORIES: Territory[] = [
  {
    id: 1,
    countyName: 'Central County',
    operatorId: 'demo-operator-001',
    operatorName: 'James Chen',
    status: 'claimed',
  },
  {
    id: 2,
    countyName: 'Metro County',
    status: 'available',
  },
  {
    id: 3,
    countyName: 'North County',
    operatorId: 'operator-other-001',
    operatorName: 'Jennifer Smith',
    status: 'claimed',
  },
  {
    id: 4,
    countyName: 'South County',
    status: 'available',
  },
  {
    id: 5,
    countyName: 'East County',
    status: 'available',
  },
  {
    id: 6,
    countyName: 'West County',
    status: 'available',
  },
  {
    id: 7,
    countyName: 'Suburban County',
    status: 'available',
  },
  {
    id: 8,
    countyName: 'Riverside County',
    status: 'available',
  },
]

export const DEMO_BID_TEMPLATES: BidTemplate[] = [
  {
    id: 'template-001',
    contractorId: 'demo-contractor-001',
    name: 'Standard Professional Bid',
    message: 'Thank you for considering my services. I have [X years] of experience in [trade type] and am fully licensed and insured. I can complete this project efficiently and to the highest standards. I\'m available to start [timeline] and will ensure all work meets or exceeds your expectations.',
    useCount: 0,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'template-002',
    contractorId: 'demo-contractor-001',
    name: 'Quick Response Template',
    message: 'I can start immediately and complete this project within [timeline]. My team is experienced, licensed, and insured. I provide a satisfaction guarantee on all work. Let\'s discuss the details!',
    useCount: 0,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'template-003',
    contractorId: 'demo-contractor-001',
    name: 'Detailed Professional Bid',
    message: 'I\'ve reviewed your project requirements and I\'m confident I can deliver excellent results. My approach includes: [detailed steps]. I\'m fully licensed, insured, and have [X] years of experience. I\'m available to discuss the project in detail and answer any questions you may have.',
    useCount: 0,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export function initializeDemoData() {
  if (demoDataInitialized) {
    return null
  }
  
  const hasInitialized = sessionStorage.getItem('demo-initialized')
  
  if (hasInitialized) {
    return null
  }
  
  demoDataInitialized = true
  sessionStorage.setItem('demo-initialized', 'true')
  
  return {
    jobs: DEMO_JOBS.slice(0, 3),
    invoices: DEMO_INVOICES.slice(0, 3),
    territories: DEMO_TERRITORIES.slice(0, 5),
    bidTemplates: DEMO_BID_TEMPLATES,
  }
}
