groups:
  - name: critical_alerts
    interval: 1m
    rules:
      - alert: HighErrorRate
        expr: job:error_rate:5m > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} (threshold: 5%)"
      
      - alert: SlowResponseTime
        expr: job:api_response_time:p95 > 2.0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "API response time is slow"
          description: "P95 response time is {{ $value }}s (threshold: 2s)"
      
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}%"
      
      - alert: DatabaseConnectionPoolExhausted
        expr: (pg_stat_database_numbackends / pg_settings_max_connections) > 0.95
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Database connection pool nearly exhausted"
          description: "{{ $value | humanizePercentage }} of connections in use"

  - name: warning_alerts
    interval: 5m
    rules:
      - alert: ModerateErrorRate
        expr: job:error_rate:5m > 0.02
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Elevated error rate"
          description: "Error rate is {{ $value | humanizePercentage }}"
      
      - alert: CacheHitRatioLow
        expr: (redis_keyspace_hits / (redis_keyspace_hits + redis_keyspace_misses)) < 0.70
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Cache hit ratio is low"
          description: "Hit ratio is {{ $value | humanizePercentage }} (target: >70%)"
      
      - alert: DiskSpaceRunningLow
        expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) > 0.80
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Disk space running low"
          description: "Disk is {{ $value | humanizePercentage }} full"
